apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-was
  namespace: ns-deploy
spec:
  selector:
    matchLabels:
      pod-type: was
  replicas: 1
  strategy:
    type: RollingUpdate
  # minReadySeconds: 10
  template:
    metadata:
      labels:
        pod-type: was
    spec:
      containers:
      - name: container
        image: progress0407/app-ver1
        resources:
          requests:
            memory: 20Mi
          limits:
            memory: 300Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 60
      terminationGracePeriodSeconds: 0