apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport
  namespace: ns-deploy
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    pod-type: was
